### ISSUE TITLE
the `kube-apiserver.log `have the literal string "(dollar_sign)Format" 

### ISSUE THREAD

**Issue by stewart-yu** [kubernetes/dns#166]
When i set up cluster with local up, the `kube-apiserver.log `have the literal string "(dollar_sign)Format" ,look like that:
```
I1113 10:09:54.443872   68028 wrap.go:42] GET /api/v1/services?resourceVersion=136&timeoutSeconds=355&watch=true: (5m55.000894913s) 200 [[kube-dns/v1.6.7 (linux/amd64) kubernetes/$Format] 172.17.0.2:58794]
I1113 10:12:05.443724   68028 wrap.go:42] GET /api/v1/endpoints?resourceVersion=256&timeoutSeconds=486&watch=true: (8m6.00068201s) 200 [[kube-dns/v1.6.7 (linux/amd64) kubernetes/$Format] 172.17.0.2:58794]
I1113 10:16:27.446941   68028 wrap.go:42] GET /api/v1/services?resourceVersion=136&timeoutSeconds=393&watch=true: (6m33.002267473s) 200 [[kube-dns/v1.6.7 (linux/amd64) kubernetes/$Format] 172.17.0.2:58794]
```
I think it related to `kube-dns` images, does anyone can help me to fix it?

**Comment by MrHohn** [comment]
This was fixed by https://github.com/kubernetes/dns/pull/163.

**Comment by stewart-yu** [comment]
I think it also not resolved. some error also in kubernetes repo.

**Comment by MrHohn** [comment]
The fix went in recently, so it will be released with the next version (1.14.8 I think).

**Comment by stewart-yu** [comment]
I see now. Thanks.
