### ISSUE TITLE
Unable to use port numbers for stubDomain servers

### ISSUE THREAD

**Issue by dpgeekzero** [kubernetes/dns#83]
When trying to setup a stubDomain to resolve to my consul cluster, I'm getting "invalid nameserver" messages

configMap data:
```
data:
  stubDomains: {"service.consul": ["100.71.68.61:8600"]}
```

The `IsDNS1123Subdomain` check on line  104 in config/config.go looks unnecessary to me.

**Comment by bdimcheff** [comment]
I think this is fixed in #69, there just hasn't been a release since that was merged.

**Comment by dpgeekzero** [comment]
Not from my reading.

**Comment by cmluciano** [comment]
@dpgeekzero Do you mean that the PR does not fix the issue that you have? 

[This test](https://github.com/kubernetes/dns/pull/69/files#diff-c72da36811e302aa5bf1f43896320c23R52) is similar to your example

**Comment by dpgeekzero** [comment]
Ahh, sorry I misread the patch.  That should take care of it.

Sorry for the noise.

**Comment by bobhenkel** [comment]
@dpgeekzero So did you get your stub to work?  What version of K8s are you on?

**Comment by bobhenkel** [comment]
Seems to work on v1.7.2.
